version: '3'

services:
  app-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app-web
#    ports:
#      - '8787:8787'
    networks:
      - internal
  app-db:
    image: mysql:8.0
    container_name: app-db
    volumes:
      - app_db:/var/lib/mysql
    restart: always
    ports:
      - '3320:3306'
    command: [ 'mysqld','--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: wontbeused
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: wontbeused
      TZ: Asia/Tehran
    networks:
      - internal
volumes:
  app_db:
    driver: local

networks:
  internal:
    external: false